version: '3'
services:
  app:
    container_name: sample-bank
    restart: always
    image: nikhilgoenka/samplebank:logmon
    ports:
      - '3000:3000'
    volumes:
      - app:/docker-compose-sample-bankApp
    external_links:
      - mongo

  mongo:
    container_name: mongo
    image: nikhilgoenka/mongo
    ports:
      - '27017:27017'

volumes:
  app:
